version: '3'

services:

  mysql-server:
    image: mysql:8.0.27
    cap_add:
      - SYS_NICE
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # credentials keycloak will you to login to the db
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - 8088:8080
    environment:
      #credentials to the keycloak console
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      KC_DB_VENDOR: MYSQL
      KC_DB: mysql-server
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_PORT: 3306
      KC_DB_USER: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_DB_DATABASE: keycloak
    depends_on:
      - mysql-server
    networks:
      - keycloak-and-mysql-network
networks:
  keycloak-and-mysql-network:
volumes:
  keycloak-and-mysql-volume:


