version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    ports:
      - 8089:8080
    environment:
      #credentials to the keycloak console
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_PORT: 3306
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_password
      DB_DATABASE: keycloak_db
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:
volumes:
  keycloak-and-mysql-volume: