#rabbitmq settings
spring:
  rabbitmq:
    host: localhost
    password: guest
    port: 15672
    username: guest
    template:
      exchange: direct.exchange
      default-receive-queue: email.q
      routing-key: email.key
#application port
server:
  port: 8081
#logger
logging:
  level:
    root: debug

#keycloak
keycloak:
  auth-server-url: http://localhost:8089
  realm: my-profile-realm
  resource: profile-ui-service
  ssl-required: external
  use-resource-role-mappings: true


#auth crede


    
   
     
    
    